{% set name = "buildbot-pkg" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9687b343918c704f69264115d164b97bf9cce636cb0d49f380d7bafb1fa6f884

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - buildbot_pkg
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://buildbot.net/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Buildbot packaging tools
  doc_url: https://docs.buildbot.net

extra:
  recipe-maintainers:
    - kszucs
    - xhochy
    - marcelotrevisani
