travis:
  secure:
    BINSTAR_TOKEN: YvzZyVl40YHZyPGcT4bzyQxwdVlxUEr76ZSzIz44Ad8XP3s9znfwqsVhwgXpZ15ktVEoBJsLaZHaQ0FanPEwlftmvQkRpfof/9w0zBrfde6V21flxM3SMlKPQwaiX/iMmwDv6OwUdRDPLJrhRzYuzJ81kEQNc3FgM4BEPSCYIIQm5d0+3hI9yYcA1KXRtI8qpsQ2BA0LN+wC3nS5DRtf21EK6BNJzmol3GuBaCccFUCA9yEVekD6bVOMLEL1uJ+KxelUjdaUKqxO6ViTZU1ouhRHrtCe0Gwo2RJjiPBQmQcW0G79vt1Tthl/yfm9gXImAeDZupCIH9JejB3ITw5Ue14DQes8Gl2Ljdwx2veQPnZC/KDOT1+8dj0UDOslrQzzaUmzwzWpzi6LqT7OBTo73WTDGd+Szk650op8aZLGLHFcvagRl3swBoVrt2uvWhVhwS8jtrY/gzGXXtq8qvshwxfxh/0zRK+0c6UMJ0VWdZp92Up1L5sz/w9aSY89nHM3CKuaIwT1KfqWn3W8+7iavOAcEe7gIov8ymirdDwExFYvMO1BYWT28OKA82MIwajiL+XK7914lf18IBrkqAKG/f96TYk8KlVaW16KGRg3xf9hApBu/3vlKz9+9viYomxibsfVXHziTEXhL/OS0gCwIrY2gM+unhsJkSGXm8Ek0sg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
